config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
   get "homes/top"
  get 'home/about', to: 'homes#about', as: 'about'


  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources  :users, only: [:index, :show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image


   validates :name, presence: true,length: {in: 2..20}
   validates :introduction,length: { maximum: 50}
   validates :name, uniqueness: true
  def email_required?
   false
  end
  def email_changed?
   false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     user_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  #def after_sign_in_path_for(resource)
   # user_path(current_user.id)

  #end

  ###end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
   before_action :ensure_current_user, {only: [:edit,:update,:destroy]}



  def new
    @book = Book.new
  end
  def show
    @user = User.find(params[:id])
    @posted_book = Book.where(user_id: params[:id])
    @books = @posted_book.all
    @book = Book.new
  end
  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if  @user.update(user_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to "/users/#{current_user.id}"
      else
            render :edit
      end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def  ensure_current_user
        @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to user_path(current_user.id)
     end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class ="col-md-8 mx-auto">
<h1>User info</h1>
<%= render 'books/error_message', model:@user %>
 <%= form_with model:@user, local:true do |f| %>
 <label for="inputName">Name</label><br>
 <%= f.text_field :name, class:"form-control", autofocus: true, id:"inputName",placeholder:"名前" %><br>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>
  <label for="inputImage">Image</label><br>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %><br>
  <label for="inputIntroduction">Introduction</label><br>
  <%= f.text_area :introduction, class:"form-control", autofocus: true, id:"inputIntroduction" %><br>
 
 <%= f.submit "Update User" %>
<% end %>
</div>
</div>

</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<%= render 'books/sidebar', book: @book, user: @user  %>
<div class="col-md-8 offset-md-1">

 <h2>Users</h2>
 <table class="table">
  <thead>
   <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %>
   <tr>
    <td><%= attachment_image_tag  user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg", class: "profile_image" %></td>
    <td><%= user.name %></td>
    <td><%= link_to "Show", user_path(user.id) %></td>
   </tr>
   <% end %>
  </tbody>
 </table>
    
</div>

</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<%= render 'books/sidebar', book: @book, user: @user  %>

<div class="col-md-8 offset-md-1">

<h2>Books</h2>

      <table class="table">
          <thead>
              <tr>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
              </tr>
          </thead>
          <tbody>
            <% if @posted_book.present? %>
              <% @books.each do |book| %>
                <tr class="book_index">
                    <th>
                      <%= link_to user_path(book.user.id) do %>
                        <%= attachment_image_tag  book.user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg", class:"profile_image" %></th>
                      <% end %>
                    <th><%= link_to book.title, book_path(book.id) %></th>
                    <th> <%= book.body %></th>
                </tr>
              <% end %>
            <% end %>  
          </tbody>
      </table>

</div>
</div>
</div>