config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
   get "homes/top"
  get 'home/about', to: 'homes#about', as: 'about'


  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources  :users, only: [:index, :show, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
	validates :title, presence: true
	validates :body, presence: true,
	                 length: { maximum: 200}


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
  
def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = (current_user.id)
      if @book.save
       flash[:notice] = "You have creatad book successfully."
       redirect_to book_path(@book.id)
      else
       @books = Book.all
       render "index"
      end
end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new

  end

  def show
    @book = Book.new
    @book_show = Book.find(params[:id])
    @user = User.find(@book_show.user_id)
  end
  def edit
    @book = Book.find(params[:id])
    unless current_user == @book.user 
      redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
      flash[:notice] = "You have update book successfully."
      redirect_to book_path(@book.id)
     else
       render "edit"
     end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def  ensure_current_user
      @book = Book.find(params[:id])
    if @book.user_id != current_user.id
        redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error_message.html.erb
<% if model.errors.any? %>
  <div class="error_explanation">
    <h3><%= pluralize(model.errors.count, "error") %>
    prohibited this obj from being saved:</h3>
    <ul class="error_message">
      <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_sidebar.html.erb
  <div class="col-md-3 ">
    <div class="sidebar" >
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image,  fallback: "no_image.jpg", size:'100x100'  %>
      <div class="d-flex">
       <p>name :</p>
       <%= user.name %>
       </div>
       <div class="d-flex">
       <p>introduction :</p>
       <%= user.introduction %>
       </div>
      
       <%= link_to edit_user_path(user) do %>
       <i class="btn btn-outline-secondary btn-block fas ffas fa-user-cog"></i>
       <% end %>
       

<h2>New book</h2>
       <%= form_with model: book,  local:true do |f| %>
       <p>Title</p>
      <%= f.text_field :title %>

       <p>Opinion</p>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book', class:"btn btn-success"  %>
      <% end %>
      
         </div>

  </div>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class ="col-md-8 mx-auto">
  
<h1>Editing Book</h1>
<%= render 'books/error_message', model:@book %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h5>Title</h5>

  <%= f.text_field :title, class:"form-control" %>

  <h5>Opinion</h5>
  <%= f.text_area :body, class:"form-control" %>
  <div>
  <%= f.submit 'Update Book',class:"btn btn-md btn-success" %>
<% end %>
<br>
<%= link_to "Show",book_path(params[:id])%>
|
<%= link_to "Back",books_path %>
</div>

</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 
 <%= render 'books/error_message', model: @book %>
<div class="row">
<%= render 'sidebar', book: @book, user: @user  %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>

 <table class="table">
  <thead>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
   </tr>
  </thead>
 <tbody>
   <% @books.each do |book| %>
   <tr class="book_index">
    <td>
    <%= link_to user_path(book.user.id) do %>
    <%= attachment_image_tag  book.user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg", class: "profile_image" %>
    <% end %>
    </td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
   </tr>
   <% end %> 
 </tbody>
 </table>

</div>
</div>
</div>

app/views/books/new.html.erb
 <h2>New book</h2>
       <%= form_with model: @book, local:true do |f| %>
       <p>Title</p>
      <%= f.text_field :title %>
  
       <p>Opinion</p>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book' %>
      <% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<%= render 'sidebar', book: @book, user: @user  %>
<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>

  <table class="table">
    <tbody>
      <tr>
       <td>
         <%= attachment_image_tag  @user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg", class:"profile_image" %><br>
         <%= link_to @user.name, user_path(@user.id) %>
       </td>
       <td><%= link_to @book_show.title, book_path(@book_show.id) %></td>
       <td><%= @book_show.body %></td>
       <% if current_user.id == @user.id %>
        <td><%= link_to "Edit", edit_book_path(@book_show.id), class:"btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", book_path(@book_show.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %></td>
       <% end %>
      </tr>
    </tbody>
  </table>

</div>
</div>
</div>