config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
   get "homes/top"
  get 'home/about', to: 'homes#about', as: 'about'


  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources  :users, only: [:index, :show, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <script src="https://kit.fontawesome.com/b602000ef2.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100">
<header class="bg-dark text-white shadow-sm">
<nav class="navbar navbar-expand-lg navbar-dark">
   <div class="container">
    <a href="/"><h4 class="text-white p-3">Bookers</h4></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
     <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
         <li class="nav-item">
          <%= link_to  user_path(current_user.id) , class: 'nav-link text-white' do %>
          <i class="fas fa-home"></i>Home
          <% end %>
         </li>
         <li class="nav-item">
          <%= link_to  users_path, class: 'nav-link text-white' do %>
          <i class="fas fa-users"></i>Users
          <% end %>
         </li>
         <li  class="nav-item">
          <%= link_to  books_path, class: 'nav-link text-white' do %>
          <i class="fas fa-book-open"></i>Books
          <% end %>
         </li>
         <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
          <i class="fas fa-sign-out-alt"></i>logout
          <% end %>
         </li>
        <% else %>
         <li class="nav-item">
          <%= link_to root_path, class: 'nav-link text-white' do %>
          <i class="fas fa-home"></i>Home
          <% end %>
         </li>
         <li class="nav-item">
          <%= link_to  about_path, class: 'nav-link text-white' do %>
          <i class="fas fa-link"></i>About
          <% end %>
         </li>
         <li class="nav-item">
          <%= link_to  new_user_registration_path, class: 'nav-link text-white' do %>
          <i class="fas fa-user-plus"></i>sign up
          <% end %>
         </li>
         <li class="nav-item">
          <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
          <i class="fas fa-sign-in-alt"></i>login
          <% end %>
         </li>
        <% end %>
       </ul>
     </div>
    </div>
</nav>
</header>
 <% if flash[:notice] %>
   <div class="flash">
     <%= flash[:notice] %>
   </div>
 <% end %>
<main class="mx-5">
 <%= yield %>
</main>

     <footer class="p-5 text-center">

            <p>CopyRight Infratop.inc</p>

     </footer>
  </body>
</html>